# Generated by Django 3.2 on 2021-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationuser',
            name='verification_code',
            field=models.EmailField(max_length=254),
        ),
    ]
