<<<<<<< Updated upstream
# Generated by Django 3.2 on 2021-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210930_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
=======
# Generated by Django 3.2 on 2021-11-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210930_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
>>>>>>> Stashed changes
