# Generated by Django 3.2.9 on 2021-12-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_verificationuser_userstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationuser',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
