# Generated by Django 3.2.9 on 2021-11-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userstore_is_admin_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='is_admin_store',
            field=models.BooleanField(default=False),
        ),
    ]
