# Generated by Django 3.2.9 on 2021-11-24 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211124_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
