# Generated by Django 3.2.9 on 2021-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211125_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
