# Generated by Django 3.2.9 on 2021-11-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isfinal',
            field=models.BooleanField(default=False),
        ),
    ]
