# Generated by Django 3.2.9 on 2021-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_shippingaddress_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='selectaddress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
