# Generated by Django 3.2.9 on 2021-11-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_shippingaddress_selectaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
