# Generated by Django 3.2.9 on 2021-12-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_templates_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='store',
        ),
    ]
