# Generated by Django 3.2.9 on 2021-12-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_templates_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='templates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.templates'),
        ),
    ]
