# Generated by Django 3.2.9 on 2021-12-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_shippingaddress_postalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
