# Generated by Django 3.2.9 on 2021-12-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_templates_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
