# Generated by Django 3.2.9 on 2021-12-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20211209_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstore',
            name='agree',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
