# Generated by Django 3.2.9 on 2021-12-15 14:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20211215_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descreption',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
