# Generated by Django 3.2.9 on 2021-12-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_product_descreption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstore',
            name='meli',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userstore',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
