# Generated by Django 3.2.9 on 2021-12-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
