# Generated by Django 3.2.9 on 2021-12-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20211220_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagefour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagethree',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imagetwo',
        ),
    ]
