# Generated by Django 3.2.9 on 2021-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_imageblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='confirmed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
